using System.Globalization;
using System.Text;
using System.Text.Json;

namespace AeroFortress.Framework.Cli;

/// <summary>The deterministic legs' exit codes, carried into the artifacts so a report is self-contained.</summary>
/// <param name="Doctor">The doctor's exit code (manifest + sync + build/AF* + frontend AFFE* legs).</param>
/// <param name="Tests">The proof run's exit code (<c>dotnet test</c> over the workspace).</param>
internal sealed record GateLegs(int Doctor, int Tests);

/// <summary>
/// Renders the <see cref="GateMatrix"/> three ways: a console table for the terminal, a
/// <c>VERIFICATION.md</c> that travels with the repo (the human-curated reading surface), and a
/// <c>VERIFICATION.json</c> for machines (CI, the harness fan-out). Same matrix, three faces — the
/// renderers never recompute a verdict.
/// </summary>
internal static class GateReport
{
    private static readonly JsonSerializerOptions JsonOptions = new()
    {
        WriteIndented = true,
        PropertyNamingPolicy = JsonNamingPolicy.CamelCase,
    };

    /// <summary>Whether the whole gate is green: every leg exit 0 and the matrix total.</summary>
    public static bool Green(GateMatrix matrix, GateLegs legs) =>
        legs.Doctor == 0 && legs.Tests == 0 && !matrix.Blocking;

    /// <summary>Write the per-module traceability table and the findings to <paramref name="writer"/>.</summary>
    public static void WriteConsole(GateMatrix matrix, GateLegs legs, TextWriter writer)
    {
        writer.WriteLine();
        writer.WriteLine($"gate matrix — {matrix.Rows.Count} declared criteria across "
                       + $"{matrix.Rows.Select(r => r.Module).Distinct().Count()} modules");
        foreach (var module in matrix.Rows.GroupBy(r => r.Module))
        {
            var proven = module.Count(r => r.Verdict == MatrixVerdict.Pass);
            writer.WriteLine($"  {module.Key} — {proven}/{module.Count()} proven");
            foreach (var row in module)
                writer.WriteLine($"    {row.Slice,-28} {row.CriterionId,-34} {Label(row.Verdict),-9} {FirstProof(row)}");
        }

        foreach (var orphan in matrix.OrphanProofs)
            writer.WriteLine($"  creep: [AVP(\"{orphan.CriterionId}\")] at {orphan.File} ({orphan.ClassName}.{orphan.Method}) is declared by no manifest");
        foreach (var critical in matrix.UndeclaredCritical)
            writer.WriteLine($"  undeclared: [Critical] {critical.Module}/{critical.Name} ({critical.File}) declares no criterion");
        foreach (var missing in matrix.DeclaredWithoutClass)
            writer.WriteLine($"  note: {missing.Module}/{missing.Slice} is declared in {missing.ManifestPath} but has no [Slice] class");
        foreach (var broken in matrix.MalformedManifests)
            writer.WriteLine($"  malformed: {broken.Path} — {broken.Error}");
        writer.WriteLine($"  verdict: {(Green(matrix, legs) ? "GREEN" : "RED")}");
        writer.WriteLine();
    }

    /// <summary>The repo-traveling artifact: the matrix as reviewable markdown.</summary>
    public static string Markdown(GateMatrix matrix, GateLegs legs, DateTimeOffset generatedAt)
    {
        var md = new StringBuilder();
        md.AppendLine("# Verification matrix");
        md.AppendLine();
        md.AppendLine(CultureInfo.InvariantCulture,
            $"> Generated by `af gate` on {generatedAt:yyyy-MM-dd HH:mm zzz}. Do not edit — re-run the gate to refresh.");
        md.AppendLine();
        md.AppendLine(CultureInfo.InvariantCulture,
            $"**Gate verdict: {(Green(matrix, legs) ? "GREEN" : "RED")}** — doctor exit {legs.Doctor} · tests exit {legs.Tests} · "
          + $"matrix {(matrix.Blocking ? "has findings" : "total")}.");

        foreach (var module in matrix.Rows.GroupBy(r => r.Module))
        {
            var proven = module.Count(r => r.Verdict == MatrixVerdict.Pass);
            md.AppendLine();
            md.AppendLine(CultureInfo.InvariantCulture, $"## {module.Key} — {proven}/{module.Count()} criteria proven");
            md.AppendLine();
            md.AppendLine("| Slice | Criterion | Proof | Verdict |");
            md.AppendLine("|---|---|---|---|");
            foreach (var row in module)
                md.AppendLine(CultureInfo.InvariantCulture,
                    $"| {row.Slice} | `{row.CriterionId}` | {ProofCell(row)} | {Label(row.Verdict)} |");
        }

        AppendFindings(md, matrix);
        return md.ToString();
    }

    /// <summary>The machine-readable artifact, camelCased and indented for diff-friendly commits.</summary>
    public static string Json(GateMatrix matrix, GateLegs legs, DateTimeOffset generatedAt)
    {
        var payload = new
        {
            Tool = "af gate",
            GeneratedAt = generatedAt,
            Verdict = Green(matrix, legs) ? "green" : "red",
            Legs = new { legs.Doctor, legs.Tests },
            Modules = matrix.Rows.GroupBy(r => r.Module).Select(module => new
            {
                Module = module.Key,
                Declared = module.Count(),
                Proven = module.Count(r => r.Verdict == MatrixVerdict.Pass),
                Rows = module.Select(r => new
                {
                    r.Slice,
                    Criterion = r.CriterionId,
                    Verdict = Label(r.Verdict),
                    Proofs = r.Proofs.Select(p => new { p.File, Class = p.ClassName, p.Method }),
                }),
            }),
            Findings = new
            {
                OrphanProofs = matrix.OrphanProofs.Select(p => new { Criterion = p.CriterionId, p.File, Class = p.ClassName, p.Method }),
                UndeclaredCritical = matrix.UndeclaredCritical.Select(s => new { s.Module, Slice = s.Name, s.File }),
                DeclaredWithoutClass = matrix.DeclaredWithoutClass.Select(d => new { d.Module, d.Slice, Manifest = d.ManifestPath }),
                MalformedManifests = matrix.MalformedManifests.Select(m => new { m.Path, m.Error }),
            },
        };
        return JsonSerializer.Serialize(payload, JsonOptions);
    }

    private static void AppendFindings(StringBuilder md, GateMatrix matrix)
    {
        if (!matrix.Blocking && matrix.DeclaredWithoutClass.Count == 0)
            return;

        md.AppendLine();
        md.AppendLine("## Findings");
        foreach (var orphan in matrix.OrphanProofs)
            md.AppendLine(CultureInfo.InvariantCulture,
                $"- **Creep** — `[AVP(\"{orphan.CriterionId}\")]` at `{orphan.File}` ({orphan.ClassName}.{orphan.Method}) is declared by no manifest.");
        foreach (var critical in matrix.UndeclaredCritical)
            md.AppendLine(CultureInfo.InvariantCulture,
                $"- **Undeclared critical** — `{critical.Module}/{critical.Name}` (`{critical.File}`) declares no acceptance criterion.");
        foreach (var broken in matrix.MalformedManifests)
            md.AppendLine(CultureInfo.InvariantCulture, $"- **Malformed manifest** — `{broken.Path}`: {broken.Error}");
        foreach (var missing in matrix.DeclaredWithoutClass)
            md.AppendLine(CultureInfo.InvariantCulture,
                $"- *Note* — `{missing.Module}/{missing.Slice}` is declared in `{missing.ManifestPath}` but has no `[Slice]` class yet.");
    }

    private static string Label(MatrixVerdict verdict) => verdict switch
    {
        MatrixVerdict.Pass => "pass",
        MatrixVerdict.Fail => "FAIL",
        MatrixVerdict.NotRun => "NOT-RUN",
        _ => "NO-PROOF",
    };

    private static string ProofCell(MatrixRow row) => row.Proofs.Count switch
    {
        0 => "—",
        1 => $"`{row.Proofs[0].ClassName}.{row.Proofs[0].Method}` — {row.Proofs[0].File}",
        _ => $"`{row.Proofs[0].ClassName}.{row.Proofs[0].Method}` — {row.Proofs[0].File} (+{row.Proofs.Count - 1} more)",
    };

    private static string FirstProof(MatrixRow row) =>
        row.Proofs.Count == 0 ? "—" : $"{row.Proofs[0].ClassName}.{row.Proofs[0].Method}";
}
